#include "../../include/CodeGen/CodeGen.h"
#include <sstream>
#include <set>
#include <string>

// =============================================================================
// MAIN ENTRY POINT
// =============================================================================

void CodeGenVisitor::generate(ProgramNode* program) {

    // Reset global label counter for this compiler run.
    // Required for correctness in multi-file compilation within one process.
    globalDestinedCounter = 0;

    // -------------------------------------------------------------------------
    // PRE-PASS: INCLUDES
    // Grimoire includes must appear FIRST in the C file — before all type
    // definitions — because headers may define types that our structs depend on.
    // -------------------------------------------------------------------------
    emitLine("// ============================================================");
    emitLine("// GENERATED BY CGIL COMPILER v1.0");
    emitLine("// DO NOT EDIT BY HAND");
    emitLine("// ============================================================");
    emitLine("");
    emitLine("// --- System Includes ---");
    emitLine("#include <stdint.h>");
    emitLine("#include <stdbool.h>");
    emitLine("");

    // Emit all grimoire/pact includes now, before anything else.
    emitLine("// --- Cgil Grimoire Includes ---");
    currentPhase = Phase::TYPES; // Temporarily use TYPES so GrimoireDecl emits
    for (auto& decl : program->declarations) {
        if (auto* g = dynamic_cast<GrimoireDecl*>(decl.get())) {
            g->accept(*this);
        }
    }
    emitLine("");

    // -------------------------------------------------------------------------
    // PREAMBLE: CGIL RUNTIME STRUCTURES
    // These are always emitted, regardless of what the .gil source contains.
    // They are the fundamental C types that Cgil's type system builds on.
    // -------------------------------------------------------------------------
    emitLine("// --- Cgil Runtime Structures ---");
    emitLine("// scroll: a fat pointer (address + length). Allocates no heap.");
    emitLine("typedef struct { const uint8_t* ptr; uint16_t len; } Cgil_Scroll;");
    emitLine("");

    // -------------------------------------------------------------------------
    // PHASE 1: TYPES
    // Emit rank typedefs, sigil structs, legion structs, Omen typedefs,
    // and Tuple typedefs. Everything needed to declare function signatures.
    // -------------------------------------------------------------------------
    emitLine("// ============================================================");
    emitLine("// PHASE 1: TYPE DEFINITIONS");
    emitLine("// ============================================================");
    currentPhase = Phase::TYPES;
    for (auto& decl : program->declarations) {
        decl->accept(*this);
    }
    emitLine("");

    // -------------------------------------------------------------------------
    // PHASE 2: PROTOTYPES
    // Forward-declare every spell so any spell can call any other spell
    // regardless of declaration order in the .gil source.
    // -------------------------------------------------------------------------
    emitLine("// ============================================================");
    emitLine("// PHASE 2: FUNCTION PROTOTYPES");
    emitLine("// ============================================================");
    currentPhase = Phase::PROTOTYPES;
    for (auto& decl : program->declarations) {
        decl->accept(*this);
    }
    emitLine("");

    // -------------------------------------------------------------------------
    // PHASE 3: IMPLEMENTATIONS
    // Emit leyline global variables and spell bodies.
    // -------------------------------------------------------------------------
    emitLine("// ============================================================");
    emitLine("// PHASE 3: IMPLEMENTATIONS");
    emitLine("// ============================================================");
    currentPhase = Phase::IMPLEMENTATIONS;
    for (auto& decl : program->declarations) {
        decl->accept(*this);
    }
}

// =============================================================================
// DECLARATION VISITORS
// =============================================================================

// grimoire <hardware_defs.h>;    pact <stdlib.h>;
//
// Emits angle-bracket includes (#include <path.h>) not quoted ones.
// Only emits during the pre-pass (when currentPhase == TYPES and caller
// is the explicit grimoire pre-loop in generate()). Other phases: skip.
//
// Cgil grimoire and pact both use angle-bracket includes because they reference
// system or build-tree headers, not local relative paths.
void CodeGenVisitor::visit(GrimoireDecl* node) {
    if (currentPhase != Phase::TYPES) return;
    
    if (node->isSystem) {
        emitLine("#include <" + node->path.lexeme + ">");
    } else {
        emitLine("#include \"" + node->path.lexeme + "\"");
    }
}

// rank DiskError { Timeout, HardwareFault, InvalidSector }
//
// Emits:
//   typedef uint16_t DiskError;
//   #define DiskError_Timeout       ((uint16_t)0)
//   #define DiskError_HardwareFault ((uint16_t)1)
//   #define DiskError_InvalidSector ((uint16_t)2)
//
// Variants are assigned sequential discriminants in declaration order.
// The typedef is uint16_t because that's what the Omen struct's __ruin field
// uses, and what all divine branch comparisons operate on.
void CodeGenVisitor::visit(RankDecl* node) {
    if (currentPhase != Phase::TYPES) return;

    emitLine("// rank " + node->name.lexeme);
    emitLine("typedef uint16_t " + node->name.lexeme + ";");
    for (size_t i = 0; i < node->variants.size(); ++i) {
        emitLine("#define " + node->name.lexeme + "_" + node->variants[i].lexeme +
                 " ((" + node->name.lexeme + ")" + std::to_string(i) + ")");
    }
    emitLine("");
}

// sigil Disk { stance Idle; stance Reading; stance Fault; soul16 sector_count; }
//
// Emits:
//   // Stance discriminants for Disk
//   #define Disk_Idle    ((uint16_t)0)
//   #define Disk_Reading ((uint16_t)1)
//   #define Disk_Fault   ((uint16_t)2)
//
//   typedef struct {
//       uint16_t __stance;       // implicit — always first field
//       uint16_t sector_count;
//   } Disk;
//
// Also stores stance info in stanceMap for AssignStmt to use.
void CodeGenVisitor::visit(SigilDecl* node) {
    if (currentPhase != Phase::TYPES) return;

    // Emit stance discriminant #defines and populate stanceMap.
    if (!node->stances.empty()) {
        emitLine("// Stance discriminants for sigil " + node->name.lexeme);
        std::vector<std::string> stanceNames;
        for (size_t i = 0; i < node->stances.size(); ++i) {
            std::string defineStr = "#define " + node->name.lexeme + "_" +
                                    node->stances[i].lexeme +
                                    " ((uint16_t)" + std::to_string(i) + ")";
            emitLine(defineStr);
            stanceNames.push_back(node->stances[i].lexeme);
        }
        stanceMap[node->name.lexeme] = stanceNames;
        emitLine("");
    }

    // Emit the struct typedef.
    emitLine("// sigil " + node->name.lexeme);
    emitLine("typedef struct {");
    indentLevel++;

    // The implicit __stance field is ALWAYS first per spec.
    // This guarantees predictable memory layout — other code can cast to
    // a generic "has __stance as first field" type.
    if (!node->stances.empty()) {
        emitLine("uint16_t __stance; // implicit stance discriminant — do not access directly");
    }

    // User-declared fields follow in declaration order.
    for (const auto& field : node->fields) {
        emitLine(getCType(field.type) + " " + field.name.lexeme + ";");
    }

    indentLevel--;
    emitLine("} " + node->name.lexeme + ";");
    emitLine("");

    // Emit Omen/Tuple typedefs for any bound spells.
    // This handles methods declared inside a sigil body.
    for (auto& boundSpell : node->boundSpells) {
        if (boundSpell->hasOmen && !boundSpell->returnTypes.empty()) {
            std::string successCType = getCType(boundSpell->returnTypes[0].typeToken);
            emitOmenTypedefIfNeeded(
                successCType,
                boundSpell->returnTypes[0].typeToken.lexeme,
                boundSpell->omenErrorType.lexeme
            );
        }
        if (boundSpell->returnTypes.size() > 1 || boundSpell->hasOmen) {
            emitTupleTypedefIfNeeded(boundSpell.get());
        }
    }
}

// legion SectorCache { mark16 sector_id; flow read_time; oath is_corrupted; }
//
// V1 STUB: Emitted as a standard C struct (no SoA transformation).
// The keyword 'legion' is tracked separately from 'sigil' so V2 can identify
// these nodes and apply the Structure of Arrays layout transformation.
void CodeGenVisitor::visit(LegionDecl* node) {
    if (currentPhase != Phase::TYPES) return;
    
    // Do NOT emit a C struct. Register it so VarDeclStmt can split its fields later.
    legionRegistry[node->name.lexeme] = node;
    emitLine("// legion " + node->name.lexeme + " (Registered for SoA expansion)");
}

// leyline disk_status_port: rune @ 0x1F7;
// portline disk_data_port: soul16 @ 0x1F0;
//
// leyline (MMIO):
//   Emits a global volatile pointer locked to the physical address.
//   volatile uint8_t* const disk_status_port = (volatile uint8_t*)0x1F7;
//   The 'volatile' prevents the optimizer from caching the value.
//   'const' prevents the pointer itself from being reassigned.
//
// portline (PIO):
//   Does NOT emit a C variable — x86 Port I/O is a separate address space
//   accessed only via 'in'/'out' CPU instructions. There is no C pointer that
//   maps to port I/O. Instead:
//   - Stores the port address in portlineAddressMap for use at read/write sites.
//   - Reads are intercepted in visit(IdentifierExpr*) -> emitPortlineRead().
//   - Writes are intercepted in visit(AssignStmt*) -> emitPortlineWrite().
//   - &portline_name is intercepted in visit(AddressOfExpr*) to emit the address.
void CodeGenVisitor::visit(HardwareDecl* node) {
    if (currentPhase != Phase::TYPES) return;
    if (!node->isPortline) {
        std::string cType = getCType(node->type);
        emitLine("// leyline " + node->name.lexeme + " @ " + node->address.lexeme);
        // Emits a C macro: #define vga_buffer (*(volatile uint16_t *)0xB8000)
        emitLine("#define " + node->name.lexeme + " (*(volatile " + cType + " *)" + node->address.lexeme + ")");
        emitLine("");
    } else {
        portlineAddressMap[node->name.lexeme]  = node->address.lexeme;
        portlineTypeMap[node->name.lexeme]     = node->type.lexeme;
        emitLine("// portline " + node->name.lexeme + " @ " + node->address.lexeme + " (reads/writes emit inline asm)");
        emitLine("");
    }
}

// Helper: emit a portline READ as a GCC statement expression.
// Wraps the asm in ({ ... }) so it can appear inside any C expression.
//
// rune   (8-bit):
//   ({ uint8_t __tmp; asm volatile("inb %1, %0" : "=a"(__tmp) : "d"((uint16_t)PORT)); __tmp; })
//
// soul16 (16-bit):
//   ({ uint16_t __tmp; asm volatile("inw %1, %0" : "=a"(__tmp) : "d"((uint16_t)PORT)); __tmp; })
void CodeGenVisitor::emitPortlineRead(const std::string& name) {
    std::string addr = portlineAddressMap.at(name);
    std::string type = portlineTypeMap.at(name);

    if (type == "rune") {
        emit("({ uint8_t __tmp; "
             "asm volatile(\"inb %1, %0\" : \"=a\"(__tmp) : \"d\"((uint16_t)" +
             addr + ")); __tmp; })");
    } else {
        // soul16 or addr
        emit("({ uint16_t __tmp; "
             "asm volatile(\"inw %1, %0\" : \"=a\"(__tmp) : \"d\"((uint16_t)" +
             addr + ")); __tmp; })");
    }
}

// Helper: emit a portline WRITE as inline asm.
// The value expression is passed as a pre-built string (already emitted by caller).
//
// rune   (8-bit):  asm volatile("outb %0, %1" :: "a"((uint8_t)(VAL)),  "d"((uint16_t)PORT));
// soul16 (16-bit): asm volatile("outw %0, %1" :: "a"((uint16_t)(VAL)), "d"((uint16_t)PORT));
void CodeGenVisitor::emitPortlineWrite(const std::string& name,
                                        const std::string& valExpr) {
    std::string addr = portlineAddressMap.at(name);
    std::string type = portlineTypeMap.at(name);

    if (type == "rune") {
        emit("asm volatile(\"outb %0, %1\" :: \"a\"((uint8_t)(" + valExpr + ")), "
             "\"d\"((uint16_t)" + addr + "))");
    } else {
        emit("asm volatile(\"outw %0, %1\" :: \"a\"((uint16_t)(" + valExpr + ")), "
             "\"d\"((uint16_t)" + addr + "))");
    }
}

// Helper: emit an Omen typedef if it hasn't been emitted yet.
//
// An Omen is a tagged union representing either a success value or a typed error:
//   typedef struct {
//       uint8_t __is_ruin;     // 0 = success, 1 = ruin
//       union {
//           Cgil_Scroll __value;  // success payload (type varies)
//           uint16_t    __ruin;   // error discriminant (from rank)
//       };
//   } Omen_scroll_DiskError;
//
// The naming convention: Omen_<successTypeName>_<ruinRankName>
// This must be emitted exactly once per unique combination.
void CodeGenVisitor::emitOmenTypedefIfNeeded(const std::string& successCType,
                                              const std::string& successTypeName,
                                              const std::string& ruinTypeName) {
    if (ruinTypeName.empty()) return; // No Omen if no ruin type
    std::string omenName = getOmenTypeName(successTypeName, ruinTypeName);

    if (emittedOmenTypes.count(omenName)) return; // Already emitted
    emittedOmenTypes.insert(omenName);

    emitLine("// Omen type: " + successTypeName + " | ruin<" + ruinTypeName + ">");
    emitLine("typedef struct {");
    indentLevel++;
    emitLine("uint8_t __is_ruin; // 0 = success, 1 = ruin");
    emitLine("union {");
    indentLevel++;

    //   If the success type is 'abyss' (void), there is no success payload.
    //   A C union cannot contain a void member — 'void __value;' is a fatal
    //   compile error. When the spell returns 'abyss | ruin<T>', we omit
    //   the __value field entirely. The __is_ruin flag is still meaningful:
    //   0 = success (no payload), 1 = ruin (discriminant in __ruin).
    if (successCType != "void") {
        emitLine(successCType + " __value; // success payload");
    } else {
        emitLine("// no __value: success type is abyss (void), no payload stored");
    }

    emitLine("uint16_t __ruin;          // ruin discriminant (rank variant value)");
    indentLevel--;
    emitLine("};");
    indentLevel--;
    emitLine("} " + omenName + ";");
    emitLine("");
}

// Helper: compute a Tuple typedef name from a spell's return type.
// (sigil* Disk, scroll | ruin<DiskError>) -> "Tuple_Disk_Omen_scroll_DiskError"
//
// For V1 we use a simplified naming that covers the common case of
// (sigil*, omen) tuples. Full generic naming would require deeper type analysis.
std::string CodeGenVisitor::getTupleTypeName(const SpellDecl* node) const {
    if (node->returnTypes.empty()) return "Tuple_Empty";

    std::string name = "Tuple";
    for (const auto& rt : node->returnTypes) {
        name += "_" + rt.typeToken.lexeme;
        if (rt.isPointer) name += "Ptr";
    }
    if (node->hasOmen && !node->omenErrorType.lexeme.empty()) {
        name += "_Omen_" + node->omenErrorType.lexeme;
    }
    return name;
}

// Helper: emit a Tuple struct typedef if it hasn't been emitted yet.
//
// Tuples are used as multi-value return types:
//   (sigil* Disk, scroll | ruin<DiskError>) emits:
//   typedef struct {
//       Disk* __elem0;
//       Omen_scroll_DiskError __elem1;
//   } Tuple_Disk_Omen_scroll_DiskError;
//
// The <~ rebinding in divine extracts __elem0.
// The pattern matching in divine inspects __elem1.
void CodeGenVisitor::emitTupleTypedefIfNeeded(SpellDecl* node) {
    if (node->returnTypes.size() <= 1 && !node->hasOmen) return;

    std::string tupleName = getTupleTypeName(node);
    if (emittedTupleTypes.count(tupleName)) return;
    emittedTupleTypes.insert(tupleName);

    emitLine("// Tuple return type for spell " + node->name.lexeme);
    emitLine("typedef struct {");
    indentLevel++;

    // Dynamically generate ALL tuple elements, not just 0 and 1
    for (size_t i = 0; i < node->returnTypes.size(); ++i) {
        bool isOmenSlot = (node->hasOmen && i == node->returnTypes.size() - 1);
        
        if (isOmenSlot && !node->omenErrorType.lexeme.empty()) {
            std::string successTypeName = node->returnTypes[i].typeToken.lexeme;
            std::string omenName = getOmenTypeName(successTypeName, node->omenErrorType.lexeme);
            emitLine(omenName + " __elem" + std::to_string(i) + "; // omen payload (success or ruin)");
        } else {
            std::string elemType = getCType(node->returnTypes[i].typeToken);
            if (node->returnTypes[i].isPointer) {
                emitLine(elemType + "* __elem" + std::to_string(i) + ";");
            } else {
                emitLine(elemType + " __elem" + std::to_string(i) + ";");
            }
        }
    }

    indentLevel--;
    emitLine("} " + tupleName + ";");
    emitLine("");
}

// Helper: scan the top-level body of a spell for DestinedStmt nodes.
// Only looks at the direct children of the spell body — does NOT recurse into
// nested blocks. This matches the spec: destined blocks are always declared at
// the top level of a spell body.
std::vector<DestinedStmt*> CodeGenVisitor::findDestinedBlocks(
    const std::vector<std::unique_ptr<Stmt>>& body) const
{
    std::vector<DestinedStmt*> result;
    for (const auto& stmt : body) {
        if (auto* d = dynamic_cast<DestinedStmt*>(stmt.get())) {
            result.push_back(d);
        }
    }
    return result;
}

// spell fetch_sector(...)   warden spell disk_irq()   conjure spell read_buffer(...)
//
// Emits:
//   PROTOTYPES phase: The function signature ending in ';'
//   IMPLEMENTATIONS phase: The function signature + body
//
// DESTINED BLOCK EXPANSION:
//   If the spell contains destined blocks, we use a two-pass approach:
//   1. Scan body for destined blocks, collect them into currentDestinedBlocks.
//   2. Declare a '__ret' local variable of the return type.
//   3. Walk the body. visit(YieldStmt*) checks inDestinedSpell and emits:
//        __ret = <value>; goto __destined_N;
//      instead of: return <value>;
//   4. After the body, emit destined labels in LIFO order (last declared fires first).
//   5. Final 'return __ret;' at the very end.
//
// WARDEN SPELL:
//   'warden' emits '__attribute__((interrupt))' before the function signature.
//   This tells GCC to use the interrupt calling convention (different epilogue
//   that correctly restores the x86 interrupt stack frame).
//
// CONJURE SPELL:
//   External C function declaration. No body is emitted.
//   'conjure endless' marks noreturn: '__attribute__((noreturn))'.
//
// Added returnTypes.empty() check to prevent out-of-bounds crash.
// Omen and Tuple typedefs are emitted in TYPES phase.
void CodeGenVisitor::visit(SpellDecl* node) {
    currentSpell = node;
    // --- TYPES PHASE: Emit Omen and Tuple typedefs for this spell's return type ---
    if (currentPhase == Phase::TYPES) {
        if (node->hasOmen && !node->returnTypes.empty()) {
            // Find the success type. For tuples, it's the second element.
            // For bare omens (scroll | ruin<E>), it's the first element.
            size_t successIdx = (node->returnTypes.size() > 1) ? 1 : 0;
            if (successIdx < node->returnTypes.size()) {
                std::string successCType    = getCType(node->returnTypes[successIdx].typeToken);
                std::string successTypeName = node->returnTypes[successIdx].typeToken.lexeme;
                emitOmenTypedefIfNeeded(successCType, successTypeName, node->omenErrorType.lexeme);
            }
        }
        if (node->returnTypes.size() > 1) {
            emitTupleTypedefIfNeeded(node);
        }
        return;
    }

    // --- PROTOTYPES and IMPLEMENTATIONS: Build the C function signature ---

    // Determine the C return type string.
    // For tuple-returning spells (multiple return types with optional omen):
    //   Emit the Tuple struct name.
    // For omen-only returns (single value with ruin):
    //   Emit the Omen struct name.
    // For single primitive returns:
    //   Emit the C type directly.
    // Check returnTypes.empty() before accessing [0].
    std::string returnTypeStr;
    if (node->returnTypes.size() > 1) {
        returnTypeStr = getTupleTypeName(node);
    } else if (node->hasOmen && !node->returnTypes.empty() &&
               !node->omenErrorType.lexeme.empty()) {
        returnTypeStr = getOmenTypeName(node->returnTypes[0].typeToken.lexeme,
                                        node->omenErrorType.lexeme);
    } else if (node->returnTypes.empty() ||
               node->returnTypes[0].typeToken.lexeme == "abyss") {
        returnTypeStr = "void";
    } else {
        returnTypeStr = getCType(node->returnTypes[0].typeToken);
        // Append '*' if the return type is a pointer
        if (node->returnTypes[0].isPointer) {
            returnTypeStr += "*";
        }
    }

    // The entry point 'main' must always return standard 'int' in C.
    // Cgil allows 'mark16' or 'mark32' for the user, but we force 'int' for GCC.
    if (node->name.lexeme == "main") {
        returnTypeStr = "int";
    }

    // Build the full signature string.
    std::string signature;

    if (node->isConjure && node->isEndless) {
        signature += "__attribute__((noreturn)) ";
    }
    if (node->isWarden && currentPhase == Phase::IMPLEMENTATIONS) {
        signature += "__attribute__((interrupt)) ";
    }

    signature += returnTypeStr + " " + node->name.lexeme + "(";

    // GCC requires ISRs to take an irq_frame argument
    if (node->isWarden) {
        signature += "void* __irq_frame"; 
    } else {
        for (size_t i = 0; i < node->params.size(); ++i) {
            const auto& p = node->params[i];
            signature += getCType(p.type);
            if (p.isPointer) signature += "*";
            signature += " " + p.name.lexeme;
            if (i < node->params.size() - 1) signature += ", ";
        }
    }
    signature += ")";

    if (currentPhase == Phase::PROTOTYPES) {
        if (node->isConjure) {
            emitLine("extern " + signature + ";");
        } else {
            emitLine(signature + ";");
        }
        return;
    }

    // --- IMPLEMENTATIONS PHASE: Emit body ---

    // conjure spells are extern declarations with no body.
    if (node->isConjure) {
        emitLine("// extern: " + node->name.lexeme + " (declared via conjure)");
        return;
    }

    // Store return type for YieldStmt to use.
    currentReturnTypeName = returnTypeStr;

    // Populate stancePointerVars: track which parameters are sigil pointers.
    // This is used by AssignStmt to decide -> vs . for __stance access.
    stancePointerVars.clear();
    for (const auto& p : node->params) {
        if (p.isPointer) {
            stancePointerVars.insert(p.name.lexeme);
        }
    }

    // Two-pass destined block handling.
    // Pass 1: Find all destined blocks in this spell body.
    currentDestinedBlocks = findDestinedBlocks(node->body);
    inDestinedSpell = !currentDestinedBlocks.empty();

    // PLAN D: Atomic label index allocation.
    // Capture the base index for this spell's destined labels BEFORE any
    // body emission runs. Increment the global counter by the full block count
    // immediately so PostfixExpr's goto calculation is stable throughout.
    //
    // All subsequent label references within this spell use currentSpellDestinedBase,
    // NOT globalDestinedCounter (which continues to mutate as more spells are emitted).
    if (inDestinedSpell) {
        currentSpellDestinedBase = globalDestinedCounter;
        globalDestinedCounter += (int)currentDestinedBlocks.size();
    } else {
        currentSpellDestinedBase = 0;
    }

    emitLine(signature + " {");
    indentLevel++;

    // If there are destined blocks, declare the unified return slot __ret.
    // Every yield will assign to __ret and jump to the destined chain.
    if (inDestinedSpell && returnTypeStr != "void") {
        // Zero-initialize __ret so that any codepath that falls through to the
        // destined chain without explicitly assigning produces defined C behavior.
        // In GNU C11, = {0} correctly zero-initializes scalars, structs, and unions.
        // This also suppresses GCC's -Wuninitialized on the 'return __ret;' at chain end.
        emitLine(returnTypeStr + " __ret = {0}; // zero-initialized unified return slot");
        emitLine("");
    }

    // Pass 2: Walk the body. Destined blocks themselves are skipped inline
    // (they will be emitted AFTER the body as labels, not where they appear).
    for (auto& stmt : node->body) {
        // Skip destined blocks during the main body pass.
        // They are emitted at the END of the function.
        if (dynamic_cast<DestinedStmt*>(stmt.get())) continue;
        stmt->accept(*this);
    }

    // Emit destined cleanup labels in LIFO order (last declared fires first).
    // LIFO: emit the last element first, chain falls through to earlier labels.
    if (inDestinedSpell) {
        emitLine("");
        emitLine("// --- Destined RAII Cleanup Chain (LIFO order) ---");

        // PLAN D: Use currentSpellDestinedBase (captured atomically before body emission).
        // globalDestinedCounter was already incremented at the start of this spell.

        // LIFO: iterate in reverse (last declared = highest index = emitted first).
        for (int i = (int)currentDestinedBlocks.size() - 1; i >= 0; --i) {
            DestinedStmt* d = currentDestinedBlocks[i];
            int labelIdx = currentSpellDestinedBase + i;

            // The label that yields jump to.
            // Label falls through to the next (lower-numbered) label automatically.
            emitLine("__destined_" + std::to_string(labelIdx) + ":;");

            if (d->hasCondition) {
                indent(); emit("if (");
                d->condition->accept(*this);
                emit(") {\n");
                indentLevel++;
                for (auto& s : d->body->statements) s->accept(*this);
                indentLevel--;
                emitLine("}");
            } else {
                for (auto& s : d->body->statements) s->accept(*this);
            }
        }

        // The final return of the unified slot.
        if (returnTypeStr != "void") {
            emitLine("return __ret;");
        } else {
            emitLine("return;");
        }
    }

    // Clean up spell state.
    inDestinedSpell = false;
    currentDestinedBlocks.clear();
    stancePointerVars.clear();
    legionArrayVars.clear();
    currentSpellDestinedBase = 0; 

    indentLevel--;
    emitLine("}");
    emitLine("");
}

// =============================================================================
// STATEMENT VISITORS
// =============================================================================

// { statements... }
//
// Emits a C block. The opening { is emitted by this visitor (not the caller).
// This is the "Allman style" brace placement.
// Called from: IfStmt, WhirlStmt, ForeStmt, and standalone block statements.
//
// NOTE: SpellDecl bodies are NOT routed through BlockStmt — they are iterated
// directly in visit(SpellDecl*) so the spell can implement the destined pattern.
void CodeGenVisitor::visit(BlockStmt* node) {
    if (currentPhase != Phase::IMPLEMENTATIONS) return;
    emitLine("{");
    indentLevel++;
    for (auto& stmt : node->statements) {
        stmt->accept(*this);
    }
    indentLevel--;
    emitLine("}");
}

// An expression used as a statement: process_data(data);
// Evaluates the expression for its side effects. Return value discarded.
void CodeGenVisitor::visit(ExprStmt* node) {
    if (currentPhase != Phase::IMPLEMENTATIONS) return;
    indent();
    node->expression->accept(*this);
    emit(";\n");
}

// Handles two cases:
//
// CASE 1 — STANCE TRANSITION: ctrl = Disk:Reading;
//   The right side is a stance reference (IdentifierExpr with stanceName set).
//   This is NOT a value assignment. It is a hardware state machine transition.
//   The __stance field in the C struct is updated to the discriminant value.
//
//   For pointer variables (own sigil*): ctrl->__stance = Disk_Reading;
//   For value variables (stack sigil):  my_disk.__stance = Disk_Idle;
//
// CASE 2 — PORTLINE WRITE: disk_status_port = target;
//   The left side is a portline variable. Cannot be assigned via C pointer.
//   Must emit: asm volatile("outb %0, %1" :: ...)
//
// CASE 3 — NORMAL ASSIGNMENT: sector_count = sector_count + 1;
//   Standard C assignment.
void CodeGenVisitor::visit(AssignStmt* node) {
    if (currentPhase != Phase::IMPLEMENTATIONS) return;

    // --- CASE 1: Stance Transition (right side is Disk:Reading etc.) ---
    auto* valIdent = dynamic_cast<IdentifierExpr*>(node->value.get());
    if (valIdent && !valIdent->stanceName.lexeme.empty()) {
        // Right side is a stance reference. Emit __stance update.
        indent();

        // Get the target variable name to check if it's a pointer.
        auto* targetIdent = dynamic_cast<IdentifierExpr*>(node->target.get());
        std::string stanceConstant = valIdent->token.lexeme + "_" + valIdent->stanceName.lexeme;

        if (targetIdent) {
            bool isPointer = stancePointerVars.count(targetIdent->token.lexeme) > 0;
            if (isPointer) {
                // Pointer access: ctrl->__stance = Disk_Reading;
                emit(targetIdent->token.lexeme + "->__stance = " + stanceConstant + ";\n");
            } else {
                // Value access: my_disk.__stance = Disk_Idle;
                emit(targetIdent->token.lexeme + ".__stance = " + stanceConstant + ";\n");
            }
        } else {
            // Complex target (member access etc.) — emit target expression then ->__stance.
            node->target->accept(*this);
            emit("->__stance = " + stanceConstant + ";\n");
        }
        return;
    }

    // --- CASE 2: Portline Write (left side is a portline variable) ---
    auto* targetIdent = dynamic_cast<IdentifierExpr*>(node->target.get());
    if (targetIdent && isPortline(targetIdent->token.lexeme)) {
        // Capture the value expression as a string by temporarily redirecting output.
        // This lets us pass the value into the outb/outw asm template.
        // (V1: We emit the asm with the raw value expression inline instead of redirecting)
        // std::ostringstream valStream;
        // std::ostream* prevOut = &out;
        // For V1: emit the asm with the raw value expression inline.
        indent();
        std::string port = targetIdent->token.lexeme;
        std::string addr = portlineAddressMap.at(port);
        std::string type = portlineTypeMap.at(port);

        // Build value string by visiting the value node (this writes to out).
        // We emit the full asm directly to avoid the redirect problem.
        if (type == "rune") {
            emit("asm volatile(\"outb %0, %1\" :: \"a\"((uint8_t)(");
            node->value->accept(*this);
            emit(")), \"d\"((uint16_t)" + addr + "));\n");
        } else {
            emit("asm volatile(\"outw %0, %1\" :: \"a\"((uint16_t)(");
            node->value->accept(*this);
            emit(")), \"d\"((uint16_t)" + addr + "));\n");
        }
        return;
    }

    // --- CASE 3: Normal Assignment ---
    indent();
    node->target->accept(*this);
    emit(" = ");
    node->value->accept(*this);
    emit(";\n");
}

// yield (ctrl, data);    yield 0;    yield;
//
// TWO MODES depending on whether the enclosing spell has destined blocks:
//
// MODE A — Normal (no destined blocks): emit 'return <value>;'
//
// MODE B — Destined mode (inDestinedSpell = true):
//   Emit: __ret = <value>;
//         goto __destined_N;    (N = index of the FIRST destined label = LIFO entry)
//
//   This ensures the destined cleanup chain always fires before the function
//   actually returns, regardless of which yield path executes.
//
// TUPLE YIELD: For multi-value yields like yield (ctrl, data):
//   Emit a compound literal initializing the Tuple struct:
//   __ret = (Tuple_Disk_Omen_scroll_DiskError){ ctrl, data };
void CodeGenVisitor::visit(YieldStmt* node) {
    if (currentPhase != Phase::IMPLEMENTATIONS) return;

    if (node->values.empty() && (!currentSpell->hasOmen || currentSpell->returnTypes.size() > 1)) {
        if (inDestinedSpell) {
            int lifoEntryLabel = currentSpellDestinedBase + (int)currentDestinedBlocks.size() - 1;
            emitLine("goto __destined_" + std::to_string(lifoEntryLabel) + ";");
        } else {
            emitLine("return;");
        }
        return;
    }

    indent();
    if (inDestinedSpell) emit("__ret = ");
    else emit("return ");

    if (currentSpell->returnTypes.size() > 1) {
        // TUPLE RETURN: Map values to __elemX fields explicitly
        emit("(" + currentReturnTypeName + "){ ");
        for (size_t i = 0; i < currentSpell->returnTypes.size(); ++i) {
            if (i > 0) emit(", ");
            emit(".__elem" + std::to_string(i) + " = ");

            bool isOmenSlot = (currentSpell->hasOmen && i == currentSpell->returnTypes.size() - 1);

            if (i < node->values.size()) {
                // Explicitly provided value
                Expr* val = node->values[i].get();
                if (isOmenSlot) {
                    std::string omenTypeStr = getOmenTypeName(currentSpell->returnTypes[i].typeToken.lexeme, currentSpell->omenErrorType.lexeme);
                    bool isRuin = false;
                    if (auto* call = dynamic_cast<CallExpr*>(val)) {
                        if (auto* id = dynamic_cast<IdentifierExpr*>(call->callee.get())) {
                            if (id->token.lexeme == "ruin") isRuin = true;
                        }
                    }
                    emit("(" + omenTypeStr + ")");
                    if (isRuin) {
                        val->accept(*this);
                    } else {
                        bool isAbyss = (currentSpell->returnTypes[i].typeToken.lexeme == "abyss");
                        if (isAbyss) emit("{ .__is_ruin = 0 }"); // Payloadless
                        else { emit("{ .__is_ruin = 0, .__value = "); val->accept(*this); emit(" }"); }
                    }
                } else {
                    val->accept(*this);
                }
            } else if (isOmenSlot) {
                // Missing value for Omen slot -> Implicit Payloadless Success
                std::string omenTypeStr = getOmenTypeName(currentSpell->returnTypes[i].typeToken.lexeme, currentSpell->omenErrorType.lexeme);
                emit("(" + omenTypeStr + "){ .__is_ruin = 0 }");
            } else {
                emit("0"); // Fallback for mismatched non-omen slots
            }
        }
        emit(" }");
    } else {
        // SINGLE RETURN OR BARE OMEN
        if (node->values.empty() && currentSpell->hasOmen) {
            emit("(" + currentReturnTypeName + "){ .__is_ruin = 0 }");
        } else if (!node->values.empty()) {
            Expr* val = node->values[0].get();
            if (currentSpell->hasOmen) {
                bool isRuin = false;
                if (auto* call = dynamic_cast<CallExpr*>(val)) {
                    if (auto* id = dynamic_cast<IdentifierExpr*>(call->callee.get())) {
                        if (id->token.lexeme == "ruin") isRuin = true;
                    }
                }
                emit("(" + currentReturnTypeName + ")");
                if (isRuin) {
                    val->accept(*this);
                } else {
                    bool isAbyss = (currentSpell->returnTypes[0].typeToken.lexeme == "abyss");
                    if (isAbyss) emit("{ .__is_ruin = 0 }"); // Payloadless
                    else { emit("{ .__is_ruin = 0, .__value = "); val->accept(*this); emit(" }"); }
                }
            } else {
                val->accept(*this);
            }
        }
    }
    
    emit(";\n");

    if (inDestinedSpell) {
        int lifoEntryLabel = currentSpellDestinedBase + (int)currentDestinedBlocks.size() - 1;
        emitLine("goto __destined_" + std::to_string(lifoEntryLabel) + ";");
    }
}

// shatter; -> break;
void CodeGenVisitor::visit(ShatterStmt* /*node*/) {
    if (currentPhase != Phase::IMPLEMENTATIONS) return;
    emitLine("break;");
}

// surge; -> continue;
void CodeGenVisitor::visit(SurgeStmt* /*node*/) {
    if (currentPhase != Phase::IMPLEMENTATIONS) return;
    emitLine("continue;");
}

// if (condition) { } elif (condition) { } else { }
//
// Emits:
//   if (condition) {
//       ...
//   } else if (condition) {
//       ...
//   } else {
//       ...
//   }
void CodeGenVisitor::visit(IfStmt* node) {
    if (currentPhase != Phase::IMPLEMENTATIONS) return;

    indent(); emit("if (");
    node->condition->accept(*this);
    emit(") {\n");
    indentLevel++;
    for (auto& s : node->thenBranch->statements) s->accept(*this);
    indentLevel--;
    emitLine("}");

    for (auto& elif : node->elifBranches) {
        indent(); emit("else if (");
        elif.condition->accept(*this);
        emit(") {\n");
        indentLevel++;
        for (auto& s : elif.body->statements) s->accept(*this);
        indentLevel--;
        emitLine("}");
    }

    if (node->elseBranch) {
        emitLine("else {");
        indentLevel++;
        for (auto& s : node->elseBranch->statements) s->accept(*this);
        indentLevel--;
        emitLine("}");
    }
}

// fore (mark16 i = 0; i < 10; i++) { }
// -> for (int16_t i = 0; i < 10; i++) { }
void CodeGenVisitor::visit(ForeStmt* node) {
    if (currentPhase != Phase::IMPLEMENTATIONS) return;

    indent();
    emit("for (" + getCType(node->initType) + " " + node->initVar.lexeme + " = ");
    node->initValue->accept(*this);
    emit("; ");
    node->condition->accept(*this);
    emit("; ");
    if (node->increment) {
        node->increment->accept(*this);
    }
    emit(") {\n");
    indentLevel++;
    for (auto& s : node->body->statements) s->accept(*this);
    indentLevel--;
    emitLine("}");
}
// whirl (condition) { } -> while (condition) { }
void CodeGenVisitor::visit(WhirlStmt* node) {
    if (currentPhase != Phase::IMPLEMENTATIONS) return;

    indent(); emit("while (");
    node->condition->accept(*this);
    emit(") {\n");
    indentLevel++;
    for (auto& s : node->body->statements) s->accept(*this);
    indentLevel--;
    emitLine("}");
}

// destined (condition) { cleanup; }
//
// This visitor is intentionally a NO-OP for inline emission.
//
// Destined blocks are NOT emitted where they appear in the source.
// They are collected by findDestinedBlocks() and emitted at the END of the
// enclosing spell body as goto labels. visit(SpellDecl*) handles this.
//
// This visitor handles the rare case of a destined block outside a spell context
// (which should not happen — the semantic analyzer would have caught it).
void CodeGenVisitor::visit(DestinedStmt* node) {
    // Intentionally empty. Emitted by visit(SpellDecl*) at the end of the spell.
    // See: currentDestinedBlocks and the destined chain emission in SpellDecl.
    (void)node;
}

// my_disk <~ divine fetch_sector(own &my_disk, 0x0500) {
//     (ctrl, scroll data)                    => { ... }
//     (ctrl, ruin<DiskError::HardwareFault>) => { ... }
//     (ctrl, ruin err)                       => { ... }
// }
//
// Canonical expansion per spec (from Context.md):
//
//   Tuple_T __result = fetch_sector(&my_disk, 0x0500);
//   my_disk = __result.__elem0;                        // <~ rebinding
//   if (!__result.__elem1.__is_ruin) {                 // success branch
//       Cgil_Scroll data = __result.__elem1.__value;
//       process_data(data);
//   } else if (__result.__elem1.__ruin == 1) {         // specific ruin
//       kernel_panic(...);
//   } else {                                           // catch-all
//       uint16_t err = __result.__elem1.__ruin;
//   }
//
void CodeGenVisitor::visit(DivineStmt* node) {
    if (currentPhase != Phase::IMPLEMENTATIONS) return;

    emitLine("{ // --- divine block scope ---");
    emitLine("/* --- divine: pattern match on Omen + ownership rebinding --- */");

    indent();
    emit("__auto_type __result = ");
    node->spellCall->accept(*this);
    emit(";\n");

    bool isPointer = stancePointerVars.count(node->targetVar.lexeme) > 0;
    if (isPointer) {
        emitLine(node->targetVar.lexeme + " = __result.__elem0; /* <~ ownership rebound */");
    } else {
        emitLine(node->targetVar.lexeme + " = *(__result.__elem0); /* <~ ownership rebound (deref) */");
    }
    emitLine("");

    // Save the outer set so branch variables don't permanently pollute the spell
    auto outerStancePointerVars = stancePointerVars;

    bool isFirst = true;
    for (auto& branch : node->branches) {
        // Reset to the outer scope before each branch, then add the branch owner
        stancePointerVars = outerStancePointerVars;
        stancePointerVars.insert(branch.ownerVar.lexeme);
        
        indent();

        if (!branch.isRuin) {
            if (!isFirst) emit("else ");
            emit("if (!__result.__elem1.__is_ruin) { /* success */\n");
            indentLevel++;
            emitLine("__auto_type " + branch.ownerVar.lexeme + " = __result.__elem0; /* local alias */");

            if (!branch.isPayloadless) {
                std::string successCType = getCType(branch.successType);
                if (successCType != "void") {
                    emitLine(successCType + " " + branch.successVar.lexeme + " = __result.__elem1.__value;");
                }
            }

            for (auto& s : branch.body->statements) s->accept(*this);
            indentLevel--;
            emitLine("}");

        } else if (branch.isSpecificRuin) {
            if (!isFirst) emit("else ");
            emit("if (__result.__elem1.__is_ruin && __result.__elem1.__ruin == " +
                 branch.rankName.lexeme + "_" + branch.variantName.lexeme + ") {\n");
            indentLevel++;
            emitLine("__auto_type " + branch.ownerVar.lexeme + " = __result.__elem0; /* local alias */");
            for (auto& s : branch.body->statements) s->accept(*this);
            indentLevel--;
            emitLine("}");

        } else {
            if (!isFirst) emit("else ");
            emit("{ /* catch-all ruin */\n");
            indentLevel++;
            emitLine("__auto_type " + branch.ownerVar.lexeme + " = __result.__elem0; /* local alias */");
            emitLine("uint16_t " + branch.catchAllVar.lexeme + " = __result.__elem1.__ruin;");
            for (auto& s : branch.body->statements) s->accept(*this);
            indentLevel--;
            emitLine("}");
        }
        isFirst = false;
    }
    emitLine("");
    // Restore the outer scope map
    stancePointerVars = outerStancePointerVars;
    emitLine("} // --- end divine block ---");
}

void CodeGenVisitor::visit(VarDeclStmt* node) {
    if (currentPhase != Phase::IMPLEMENTATIONS) return;

    std::string cType = getCType(node->typeToken);

    if (node->isArray) {
        // Is this an array of a legion?
        if (legionRegistry.count(node->typeToken.lexeme)) {
            indent();
            emitLine("/* SoA Expansion for legion: " + node->name.lexeme + " */");
            legionArrayVars.insert(node->name.lexeme); // Track for DOT interception
            
            LegionDecl* legion = legionRegistry[node->typeToken.lexeme];
            for (const auto& field : legion->fields) {
                emitLine(getCType(field.type) + " " + node->name.lexeme + "_" + field.name.lexeme +
                         "[" + node->arraySizeToken.lexeme + "];");
            }
        } else {
            // Normal array declaration
            indent();
            emit(cType + " " + node->name.lexeme + "[" + node->arraySizeToken.lexeme + "]");
            if (node->initializer) {
                emit(" = ");
                node->initializer->accept(*this);
            }
            emit(";\n");
        }
    } else if (node->isPointer) {
        // Pointer declaration: mark16* px = &x;   sigil* Device ptr = &dev;
        // Emits: int16_t* px = &x;   Device* ptr = &dev;
        indent();
        emit(cType + "* " + node->name.lexeme);
        if (node->initializer) {
            emit(" = ");
            node->initializer->accept(*this);
        }
        emit(";\n");

        // Register local sigil pointers so AssignStmt emits ->__stance
        stancePointerVars.insert(node->name.lexeme);

    } else {
        // Scalar declaration: mark16 x = 5;
        // Emits: int16_t x = 5;
        indent();
        emit(cType + " " + node->name.lexeme);
        if (node->initializer) {
            emit(" = ");
            node->initializer->accept(*this);
        }
        emit(";\n");
    }
}

// Postfix '?' — Omen unpack operator.
//
// PHASE 3 FULL IMPLEMENTATION (using resolvedOmenType):
// Emits a GNU statement expression that:
//   1. Evaluates the Omen expression exactly once (no double evaluation).
//   2. Checks __is_ruin — if true, propagates the ruin immediately.
//   3. If success and the Omen has a __value (not abyss), yields the __value.
//
// The resolvedOmenType field (set by SemanticAnalyzer) tells us:
//   - The concrete Omen typedef name (e.g., "Omen_scroll_DiskError") for _tmp.
//   - Whether the success type is abyss (no __value in the union).
//
// Ruin propagation path:
//   - If inDestinedSpell: emit  __ret = _tmp; goto __destined_N;
//   - Otherwise:          emit  return _tmp;   (direct early return)
//
// gnu11 target note: Statement expressions `({ ... })` and __auto_type are
// GNU extensions. This is correct for bare-metal GCC targets.
void CodeGenVisitor::visit(PostfixExpr* node) {
    if (currentPhase != Phase::IMPLEMENTATIONS) return;
    if (!currentSpell) return;

    std::string tmpType = "__auto_type";
    bool isAbyssOmen = false;

    if (node->resolvedOmenType) {
        if (node->resolvedOmenType->successType) {
            isAbyssOmen = (node->resolvedOmenType->successType->name == "abyss" ||
                           (node->resolvedOmenType->successType->kind == TypeKind::PRIMITIVE &&
                            node->resolvedOmenType->successType->name == "abyss"));
        }
        if (!node->resolvedOmenType->name.empty() && node->resolvedOmenType->name != "Omen") {
            tmpType = node->resolvedOmenType->name;
        }
    }

    emit("({ ");
    emit(tmpType + " _omen_tmp_ = ");
    node->operand->accept(*this);
    emit("; ");
    emit("if (_omen_tmp_.__is_ruin) { ");

    // Type-Matching Early Return Resolver
    std::string rhs;
    if (currentSpell->returnTypes.size() > 1) {
        rhs = "(" + currentReturnTypeName + "){ ";
        std::set<std::string> usedParams; // Track consumed parameters
        
        for (size_t i = 0; i < currentSpell->returnTypes.size(); ++i) {
            if (i > 0) rhs += ", ";
            rhs += ".__elem" + std::to_string(i) + " = ";

            // Is this the final element AND the spell has an Omen?
            if (i == currentSpell->returnTypes.size() - 1 && currentSpell->hasOmen) {
                std::string expectedOmen = getOmenTypeName(currentSpell->returnTypes[i].typeToken.lexeme, currentSpell->omenErrorType.lexeme);
                rhs += "(" + expectedOmen + "){ .__is_ruin = 1, .__ruin = _omen_tmp_.__ruin }";
            } else {
                // PATCH 3: Use the ownership parameter name bound by the SA
                if (!node->ownershipParamName.empty()) {
                    rhs += node->ownershipParamName;
                } else {
                    rhs += "0"; // Defensive fallback
                }
            }
        }
        rhs += " }";
    } else {
        rhs = "(" + currentReturnTypeName + "){ .__is_ruin = 1, .__ruin = _omen_tmp_.__ruin }";
    }

    if (inDestinedSpell && !currentDestinedBlocks.empty()) {
        int lastDeclared = currentSpellDestinedBase + (int)currentDestinedBlocks.size() - 1;
        emit("__ret = " + rhs + "; goto __destined_" + std::to_string(lastDeclared) + "; ");
    } else {
        emit("return " + rhs + "; ");
    }
    emit("} ");

    // STATEMENT EXPRESSION END: Yields the value or 0 cleanly.
    if (isAbyssOmen) { emit("0; "); } else { emit("_omen_tmp_.__value; "); }
    emit("})");
}

// =============================================================================
// EXPRESSION VISITORS
// Expressions emit inline — NO newlines, NO semicolons.
// They are always called from within a statement visitor that handles
// the surrounding indent/newline/semicolon.
// =============================================================================

// Binary infix operations.
//
// WEAVE (~>) SPECIAL CASE:
//   a ~> f(b, c) translates to f(a, b, c)
//   The right side is always a CallExpr. We pull the left expression into
//   the argument list as the first argument.
//   Note: If the right side already has its arguments, we emit:
//     right_callee(left, right_args...)
//
// ARROW (->) and DOT (.):
//   Direct C equivalents. Emit the operator without surrounding spaces.
//
// ALL OTHER OPERATORS:
//   Emit with spaces: (left op right)
void CodeGenVisitor::visit(BinaryExpr* node) {
    if (currentPhase != Phase::IMPLEMENTATIONS) return;

    if (node->op.type == TokenType::WEAVE) {
        auto* callRight = dynamic_cast<CallExpr*>(node->right.get());
        if (callRight) {
            callRight->callee->accept(*this);
            emit("(");
            node->left->accept(*this);
            for (size_t i = 0; i < callRight->args.size(); ++i) {
                emit(", ");
                callRight->args[i]->accept(*this);
            }
            emit(")");
        } else {
            node->right->accept(*this);
            emit("(");
            node->left->accept(*this);
            emit(")");
        }
        return;
    }

    // --- SoA INTERCEPTOR ---
    // MUST happen before ANY parenthesis or left-side emission!
    if (node->op.type == TokenType::DOT) {
        if (auto* idx = dynamic_cast<IndexExpr*>(node->left.get())) {
            if (auto* targetIdent = dynamic_cast<IdentifierExpr*>(idx->target.get())) {
                if (legionArrayVars.count(targetIdent->token.lexeme)) {
                    auto* field = dynamic_cast<IdentifierExpr*>(node->right.get());
                    if (field) {
                        // Emit ONLY: arrayName_fieldName[index]
                        emit(targetIdent->token.lexeme + "_" + field->token.lexeme + "[");
                        idx->index->accept(*this);
                        emit("]");
                        return; // Stop standard emission completely!
                    }
                }
            }
        }
    }
    // --- END SoA INTERCEPTOR ---

    emit("(");
    node->left->accept(*this);

    if (node->op.type == TokenType::ARROW || node->op.type == TokenType::DOT) {
        emit(node->op.lexeme); // -> or .
        
        auto* rightIdent = dynamic_cast<IdentifierExpr*>(node->right.get());
        // Intercept "stance" and map it to the C struct's "__stance"
        if (rightIdent && rightIdent->token.lexeme == "stance") {
            emit("__stance"); 
        } else {
            node->right->accept(*this);
        }
    } else {
        std::string opStr = node->op.lexeme;
        if (node->op.type == TokenType::EQ)  opStr = "==";
        if (node->op.type == TokenType::NEQ) opStr = "!=";
        emit(" " + opStr + " ");
        node->right->accept(*this);
    }

    emit(")");
}

// Prefix unary: -x, *ptr
void CodeGenVisitor::visit(UnaryExpr* node) {
    if (currentPhase != Phase::IMPLEMENTATIONS) return;
    emit(node->op.lexeme);
    node->operand->accept(*this);
}

// Integer, string, and boolean literals.
//
// STRING LITERAL -> Cgil_Scroll compound literal:
//   ((Cgil_Scroll){ .ptr = (const uint8_t*)"text", .len = N })
//
//   LENGTH CALCULATION:
//   The lexeme contains raw source text with escape sequences stored as
//   two characters (e.g., \n = backslash + 'n'). At runtime in C, \n is
//   one byte. The len field must reflect the runtime byte count.
//   We count escape sequences and subtract: len = lexeme.length() - escapeCount.
//
// INT LITERAL -> emitted verbatim (hex literals preserved: 0x1F7)
// KEPT -> 1   FORSAKEN -> 0
void CodeGenVisitor::visit(LiteralExpr* node) {
    if (currentPhase != Phase::IMPLEMENTATIONS) return;

    if (node->token.type == TokenType::STRING_LIT) {
        // Calculate runtime byte length, accounting for escape sequences.
        const std::string& lex = node->token.lexeme;
        size_t runtimeLen = 0;
        for (size_t i = 0; i < lex.size(); ++i) {
            if (lex[i] == '\\' && i + 1 < lex.size()) {
                ++i; // skip the escaped character — one byte at runtime
            }
            ++runtimeLen;
        }

        emit("((Cgil_Scroll){ .ptr = (const uint8_t*)\"" + lex +
             "\", .len = " + std::to_string(runtimeLen) + " })");

    } else if (node->token.type == TokenType::KEPT) {
        emit("1");
    } else if (node->token.type == TokenType::FORSAKEN) {
        emit("0");
    } else {
        // Integer literal: emit verbatim (preserves hex format: 0x1F7)
        emit(node->token.lexeme);
    }
}

// Named reference to a variable, stance discriminant, or rank variant.
//
// PORTLINE READ:
//   If this identifier is a portline variable, emit inline asm instead of
//   the variable name (which does not exist as a C variable).
//   rune portline:   ({ uint8_t __tmp; asm volatile("inb ..."); __tmp; })
//   soul16 portline: ({ uint16_t __tmp; asm volatile("inw ..."); __tmp; })
//
// STANCE REFERENCE (e.g., Disk:Fault):
//   Emits: Disk_Fault (the #define constant)
//
// RANK VARIANT (e.g., DiskError::Timeout):
//   Emits: DiskError_Timeout (the #define constant)
//
// PLAIN VARIABLE:
//   Emits the identifier directly.
void CodeGenVisitor::visit(IdentifierExpr* node) {
    if (currentPhase != Phase::IMPLEMENTATIONS) return;

    // Check for portline read first.
    if (node->stanceName.lexeme.empty() && node->variantName.lexeme.empty()) {
        if (isPortline(node->token.lexeme)) {
            emitPortlineRead(node->token.lexeme);
            return;
        }
        // Plain variable.
        emit(node->token.lexeme);
        return;
    }

    if (!node->stanceName.lexeme.empty()) {
        // Stance reference: Disk:Fault -> Disk_Fault (#define constant)
        emit(node->token.lexeme + "_" + node->stanceName.lexeme);
        return;
    }

    if (!node->variantName.lexeme.empty()) {
        // Rank variant: DiskError::Timeout -> DiskError_Timeout (#define constant)
        emit(node->token.lexeme + "_" + node->variantName.lexeme);
        return;
    }
}

// Function call expression: fetch_sector(&my_disk, 0x0500)
// Special case: ruin(DiskError::HardwareFault) — Omen error construction.
//
// OWN KEYWORD STRIPPING:
//   The 'own' keyword is compile-time only (tracked by the semantic analyzer).
//   It is never emitted in C. The argument is emitted as a bare expression.
//
// RUIN CONSTRUCTION:
//   ruin(DiskError::HardwareFault) emits a tagged-union Omen struct:
//   ((Omen_T){ .__is_ruin = 1, .__ruin = DiskError_HardwareFault })
//   Note: The exact Omen type name depends on the enclosing spell's return type.
//   For V1 we use a generic emission that GCC's __auto_type will resolve.
void CodeGenVisitor::visit(CallExpr* node) {
    if (currentPhase != Phase::IMPLEMENTATIONS) return;

    auto* ident = dynamic_cast<IdentifierExpr*>(node->callee.get());

    // Special case: ruin(DiskError::HardwareFault) — Omen error construction.
    if (ident && ident->token.lexeme == "ruin") {
        std::string omenType;
        if (currentSpell && currentSpell->hasOmen) {
            if (currentSpell->returnTypes.size() > 1) {
                omenType = getOmenTypeName(currentSpell->returnTypes[1].typeToken.lexeme, currentSpell->omenErrorType.lexeme);
            } else if (!currentSpell->returnTypes.empty()) {
                omenType = getOmenTypeName(currentSpell->returnTypes[0].typeToken.lexeme, currentSpell->omenErrorType.lexeme);
            }
        }
        if (omenType.empty()) omenType = currentReturnTypeName;

        emit("(" + omenType + "){ .__is_ruin = 1, .__ruin = ");
        if (!node->args.empty()) {
            node->args[0]->accept(*this);
        }
        emit(" }");
        return;
    }

    // Standard call.
    node->callee->accept(*this);
    emit("(");
    for (size_t i = 0; i < node->args.size(); ++i) {
        // 'own' is stripped entirely — the C argument is just the expression.
        node->args[i]->accept(*this);
        if (i < node->args.size() - 1) emit(", ");
    }
    emit(")");
}

// &name — address-of operator.
//
// TWO CASES based on whether the operand is a hardware variable:
//
// HARDWARE VARIABLE (portline or leyline):
//   &portline_name -> the port address as a compile-time addr constant
//   &leyline_name  -> the physical address as a compile-time addr constant
//   e.g., &disk_data_port -> ((uint16_t)0x1F0)
//   This is NOT a C pointer dereference. It produces the address integer.
//
// REGULAR VARIABLE:
//   &my_disk -> standard C address-of operator
//   Emits: &my_disk (or &(expr) for complex left-hand sides)
void CodeGenVisitor::visit(AddressOfExpr* node) {
    if (currentPhase != Phase::IMPLEMENTATIONS) return;

    auto* ident = dynamic_cast<IdentifierExpr*>(node->operand.get());
    if (ident && portlineAddressMap.count(ident->token.lexeme)) {
        emit("((uint16_t)" + portlineAddressMap.at(ident->token.lexeme) + ")");
        return;
    }

    // Standard C address-of. We rely on cross-compilation flags to handle 
    // the 64-bit to 16-bit addr conversions for hardware variables.
    emit("&(");
    node->operand->accept(*this);
    emit(")");
}

// Array subscript: target[index]
// Emits: (target)[index]
//
// The parentheses around target prevent operator precedence issues when
// target is a complex expression (e.g., a member access or portline read).
//
// Portline arrays: if target is a portline leyline identifier, it evaluates
// to the value at the address — which is NOT an array in the C sense. This
// would be a semantic error caught by the Semantic Analyzer in V1.5.
// V1: We emit it directly and let GCC catch misuse.
void CodeGenVisitor::visit(IndexExpr* node) {
    if (currentPhase != Phase::IMPLEMENTATIONS) return;

    emit("(");
    node->target->accept(*this);
    emit(")[");
    node->index->accept(*this);
    emit("]");
}

// Struct initializer: Device:Idle { device_id: 0, error_code: 0, flags: 0 }
//
// Emits (with stance prefix):
//   (Device){ .__stance = Device_Idle, .device_id = 0, .error_code = 0, .flags = 0 }
//
// Emits (without stance prefix):
//   (Packet){ .length = 64, .checksum = 0xABCD, .type_byte = 0x01, .sequence = 100 }
//
// GNU designated initializers (.fieldname = value) are C99 and above.
// They allow any subset of fields to be specified; unspecified fields are zero-initialized.
//
// LIFETIME NOTE: This produces a compound literal with block scope lifetime.
// Safe to pass by value or by borrow to spells. Unsafe to pass to conjure spells
// by non-owned pointer if the callee retains the pointer past the statement boundary.
// (The Semantic Analyzer documents this constraint but does not enforce it in V1.)
void CodeGenVisitor::visit(StructInitExpr* node) {
    if (currentPhase != Phase::IMPLEMENTATIONS) return;

    emit("(" + node->typeName.lexeme + "){ ");

    // If a stance prefix is present, emit the __stance discriminant first.
    // This matches the sigil struct layout: __stance is always the first field.
    if (!node->stanceName.lexeme.empty()) {
        emit(".__stance = " + node->typeName.lexeme + "_" + node->stanceName.lexeme);
        if (!node->fields.empty()) emit(", ");
    }

    // Emit field initializers as GNU designated initializers.
    for (size_t i = 0; i < node->fields.size(); ++i) {
        emit("." + node->fields[i].name.lexeme + " = ");
        node->fields[i].value->accept(*this);
        if (i < node->fields.size() - 1) emit(", ");
    }

    emit(" }");
}

void CodeGenVisitor::visit(AssignExpr* node) {
    if (currentPhase != Phase::IMPLEMENTATIONS) return;

    node->target->accept(*this);
    emit(" = ");
    node->value->accept(*this);
}

void CodeGenVisitor::visit(CastExpr* node) {
    if (currentPhase != Phase::IMPLEMENTATIONS) return;

    std::string cType = getCType(node->targetType);
    if (node->isPointer) cType += "*"; // Append pointer asterisk
    
    emit("((" + cType + ")(");
    node->operand->accept(*this);
    emit("))");
}

void CodeGenVisitor::visit(UpdateExpr* node) {
    if (currentPhase != Phase::IMPLEMENTATIONS) return;

    if (node->isPrefix) emit(node->op.lexeme);  // e.g., "++"
    node->operand->accept(*this);               // e.g., "i"
    if (!node->isPrefix) emit(node->op.lexeme); // e.g., "++" (if postfix)
}