// ============================================================
// GENERATED BY CGIL COMPILER v1.0
// DO NOT EDIT BY HAND
// ============================================================

// --- System Includes ---
#include <stdint.h>
#include <stdbool.h>

// --- Cgil Grimoire Includes ---
#include <stdio.h>
#include <stdlib.h>

// --- Cgil Runtime Structures ---
// scroll: a fat pointer (address + length). Allocates no heap.
typedef struct { const uint8_t* ptr; uint16_t len; } Cgil_Scroll;

// ============================================================
// PHASE 1: TYPE DEFINITIONS
// ============================================================
#include <stdio.h>
#include <stdlib.h>
// leyline vga_buffer @ 0xB8000
#define vga_buffer (*(volatile int16_t *)0xB8000)

// portline disk_data @ 0x1F0 (reads/writes emit inline asm)


// ============================================================
// PHASE 2: FUNCTION PROTOTYPES
// ============================================================
extern int32_t putchar(int32_t c);
void print(Cgil_Scroll text);
void print_digits(int32_t val);
void print_num(int32_t val);
void print_flow(float val);
extern void exit(int32_t status);
void assert(uint8_t condition, Cgil_Scroll fail_msg);
int main();

// ============================================================
// PHASE 3: IMPLEMENTATIONS
// ============================================================
// extern: putchar (declared via conjure)
void print(Cgil_Scroll text) {
    for (int16_t i = 0; (i < (text.len)); i++) {
        putchar(((int32_t)(((text.ptr))[i])));
    }
    putchar(10);
}

void print_digits(int32_t val) {
    if ((val == 0)) {
        return;
    }
    print_digits((val / 10));
    int32_t digit = (val % 10);
    putchar((48 + digit));
}

void print_num(int32_t val) {
    if ((val == 0)) {
        putchar(48);
        putchar(10);
        return;
    }
    print_digits(val);
    putchar(10);
}

void print_flow(float val) {
    if ((val < 0.0)) {
        putchar(45);
        val = (0.0 - val);
    }
    int32_t int_part = ((int32_t)(val));
    float frac_part = (val - ((float)(int_part)));
    if ((int_part == 0)) {
        putchar(48);
    }
    else {
        print_digits(int_part);
    }
    putchar(46);
    for (int16_t i = 0; (i < 4); i++) {
        frac_part = (frac_part * 10.0);
        int32_t digit = ((int32_t)(frac_part));
        putchar((48 + digit));
        frac_part = (frac_part - ((float)(digit)));
    }
    putchar(10);
}

// extern: exit (declared via conjure)
void assert(uint8_t condition, Cgil_Scroll fail_msg) {
    if ((condition == 0)) {
        print(((Cgil_Scroll){ .ptr = (const uint8_t*)"ASSERTION FAILED:", .len = 17 }));
        print(fail_msg);
        exit(1);
    }
}

int main() {
    print(((Cgil_Scroll){ .ptr = (const uint8_t*)"RUNNING TEST 11: HARDWARE MAPPING...", .len = 36 }));
    uint16_t vga_addr = &(vga_buffer);
    uint16_t disk_addr = ((uint16_t)0x1F0);
    assert((vga_addr == 753664), ((Cgil_Scroll){ .ptr = (const uint8_t*)"Leyline address resolution failed", .len = 33 }));
    assert((disk_addr == 496), ((Cgil_Scroll){ .ptr = (const uint8_t*)"Portline address resolution failed", .len = 34 }));
    print(((Cgil_Scroll){ .ptr = (const uint8_t*)"TEST 11 SUCCESS.", .len = 16 }));
    return 0;
}

