// ============================================================
// GENERATED BY CGIL COMPILER v1.0
// DO NOT EDIT BY HAND
// ============================================================

// --- System Includes ---
#include <stdint.h>
#include <stdbool.h>

// --- Cgil Grimoire Includes ---
#include <stdio.h>

// --- Cgil Runtime Structures ---
// scroll: a fat pointer (address + length). Allocates no heap.
typedef struct { const uint8_t* ptr; uint16_t len; } Cgil_Scroll;

// ============================================================
// PHASE 1: TYPE DEFINITIONS
// ============================================================
#include <stdio.h>

// ============================================================
// PHASE 2: FUNCTION PROTOTYPES
// ============================================================
extern int32_t putchar(int32_t c);
void print(Cgil_Scroll text);

// ============================================================
// PHASE 3: IMPLEMENTATIONS
// ============================================================
// extern: putchar (declared via conjure)
void print(Cgil_Scroll text) {
    for (int16_t i = 0; (i < (text.len)); i++) {
        putchar(((int32_t)(((text.ptr))[i])));
    }
    putchar(10);
}

